[app]
app_version = "0.0.1"
env = "staging"

[blog]
grpc_port = 55101
http_port = 55102
proxy_port = 55103
log_path = "logs/blog.log"
data_path = "plugins/storages/database/blog-200315.db"

[user_service]
grpc_port = 55301
http_port = 55302
proxy_port = 55303
log_path = "logs/user.log"
default_avatar = ""
expire_token_time = 2592000 # 30 days
jwt_key = "abc"
salt_pwd = "abc"

[images]
http_port = 55201
dir_storage = "./public/images/"
form_file = "image"
log_path = "logs/images.log"

[mysql]
addr = "remotemysql.com"
user = "YsEOTRc0pD"
pass = "0dYfRSGYKT"
db_name = "YsEOTRc0pD"

[redis]
db_name = "wusblog"
addr = "redis-18633.c13.us-east-1-3.ec2.cloud.redislabs.com:18633"
pass = "tFCARObRSvMmThroNOq01xYCMpGgh9JG"
max_retries = 3 
