// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blog.proto

package blog

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_DRAFT  Status = 0
	Status_PULISH Status = 1
)

var Status_name = map[int32]string{
	0: "DRAFT",
	1: "PULISH",
}

var Status_value = map[string]int32{
	"DRAFT":  0,
	"PULISH": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

type ListRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListResponse struct {
	Code                 int64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Blogs                []*BlogData `protobuf:"bytes,3,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListResponse) GetBlogs() []*BlogData {
	if m != nil {
		return m.Blogs
	}
	return nil
}

type BlogResponse struct {
	Code                 int64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Blog                 *BlogData `protobuf:"bytes,3,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BlogResponse) Reset()         { *m = BlogResponse{} }
func (m *BlogResponse) String() string { return proto.CompactTextString(m) }
func (*BlogResponse) ProtoMessage()    {}
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}
func (m *BlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogResponse.Unmarshal(m, b)
}
func (m *BlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogResponse.Marshal(b, m, deterministic)
}
func (m *BlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogResponse.Merge(m, src)
}
func (m *BlogResponse) XXX_Size() int {
	return xxx_messageInfo_BlogResponse.Size(m)
}
func (m *BlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlogResponse proto.InternalMessageInfo

func (m *BlogResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BlogResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BlogResponse) GetBlog() *BlogData {
	if m != nil {
		return m.Blog
	}
	return nil
}

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Comment struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{5}
}
func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Comment) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type BlogData struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;AUTO_INCREMENT"`
	Title                string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Des                  string     `protobuf:"bytes,3,opt,name=des,proto3" json:"des,omitempty"`
	Content              string     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           int64      `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Status               Status     `protobuf:"varint,6,opt,name=status,proto3,enum=blog.Status" json:"status,omitempty"`
	Type                 string     `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Likes                int64      `protobuf:"varint,8,opt,name=likes,proto3" json:"likes,omitempty"`
	Views                int64      `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Comments             []*Comment `protobuf:"bytes,10,rep,name=comments,proto3" json:"comments,omitempty" gorm:"-"`
	CommentStr           string     `protobuf:"bytes,11,opt,name=commentStr,proto3" json:"commentStr,omitempty" json:"-"`
	Tags                 []string   `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" gorm:"-"`
	TagStr               string     `protobuf:"bytes,13,opt,name=tagStr,proto3" json:"tagStr,omitempty" json:"-"`
	Images               []string   `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty" gorm:"-"`
	ImagesStr            string     `protobuf:"bytes,15,opt,name=imagesStr,proto3" json:"imagesStr,omitempty" json:"-"`
	UserID               int64      `protobuf:"varint,16,opt,name=userID,proto3" json:"userID,omitempty"`
	UserAvatar           string     `protobuf:"bytes,17,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlogData) Reset()         { *m = BlogData{} }
func (m *BlogData) String() string { return proto.CompactTextString(m) }
func (*BlogData) ProtoMessage()    {}
func (*BlogData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{6}
}
func (m *BlogData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogData.Unmarshal(m, b)
}
func (m *BlogData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogData.Marshal(b, m, deterministic)
}
func (m *BlogData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogData.Merge(m, src)
}
func (m *BlogData) XXX_Size() int {
	return xxx_messageInfo_BlogData.Size(m)
}
func (m *BlogData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogData.DiscardUnknown(m)
}

var xxx_messageInfo_BlogData proto.InternalMessageInfo

func (m *BlogData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlogData) GetDes() string {
	if m != nil {
		return m.Des
	}
	return ""
}

func (m *BlogData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlogData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BlogData) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_DRAFT
}

func (m *BlogData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlogData) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *BlogData) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *BlogData) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *BlogData) GetCommentStr() string {
	if m != nil {
		return m.CommentStr
	}
	return ""
}

func (m *BlogData) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BlogData) GetTagStr() string {
	if m != nil {
		return m.TagStr
	}
	return ""
}

func (m *BlogData) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *BlogData) GetImagesStr() string {
	if m != nil {
		return m.ImagesStr
	}
	return ""
}

func (m *BlogData) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BlogData) GetUserAvatar() string {
	if m != nil {
		return m.UserAvatar
	}
	return ""
}

func init() {
	proto.RegisterEnum("blog.Status", Status_name, Status_value)
	proto.RegisterType((*ListRequest)(nil), "blog.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "blog.ListResponse")
	proto.RegisterType((*BlogResponse)(nil), "blog.BlogResponse")
	proto.RegisterType((*GetRequest)(nil), "blog.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "blog.DeleteRequest")
	proto.RegisterType((*Comment)(nil), "blog.Comment")
	proto.RegisterType((*BlogData)(nil), "blog.BlogData")
}

func init() { proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1) }

var fileDescriptor_6745b25902462fb1 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x4e, 0x1b, 0x39,
	0x14, 0xde, 0xfc, 0x0d, 0xc9, 0xc9, 0xcf, 0x06, 0xb3, 0x5a, 0x59, 0x11, 0xda, 0x64, 0x47, 0xac,
	0x84, 0xa2, 0x85, 0x48, 0x54, 0x55, 0x25, 0x50, 0xd5, 0x06, 0x02, 0x14, 0x89, 0xd2, 0x6a, 0x12,
	0xae, 0x7a, 0x41, 0x9d, 0xe4, 0x30, 0xb8, 0x64, 0xc6, 0xe9, 0xd8, 0xa1, 0x42, 0x55, 0x6f, 0xfa,
	0x0a, 0x7d, 0xa3, 0xbe, 0x42, 0xef, 0x7a, 0xc1, 0x55, 0x9f, 0x80, 0x27, 0xa8, 0x6c, 0x4f, 0xc2,
	0x84, 0x46, 0x55, 0xd5, 0xbb, 0xf3, 0xf7, 0x7d, 0x3e, 0xfe, 0x7c, 0x8e, 0x01, 0xfa, 0x23, 0xe1,
	0x6f, 0x8e, 0x23, 0xa1, 0x04, 0xc9, 0x6a, 0xbb, 0xb6, 0xea, 0x0b, 0xe1, 0x8f, 0xb0, 0xc5, 0xc6,
	0xbc, 0xc5, 0xc2, 0x50, 0x28, 0xa6, 0xb8, 0x08, 0xa5, 0xad, 0xa9, 0x6d, 0xf8, 0x5c, 0x5d, 0x4c,
	0xfa, 0x9b, 0x03, 0x11, 0xb4, 0x7c, 0xe1, 0x8b, 0x96, 0x09, 0xf7, 0x27, 0xe7, 0xc6, 0x33, 0x8e,
	0xb1, 0x6c, 0xb9, 0xbb, 0x03, 0xc5, 0x63, 0x2e, 0x95, 0x87, 0x6f, 0x27, 0x28, 0x15, 0xf9, 0x0b,
	0x72, 0x23, 0x1e, 0x70, 0x45, 0x53, 0x8d, 0xd4, 0x7a, 0xc6, 0xb3, 0x0e, 0xf9, 0x1b, 0x1c, 0x71,
	0x7e, 0x2e, 0x51, 0xd1, 0xb4, 0x09, 0xc7, 0x9e, 0xdb, 0x87, 0x92, 0x05, 0xcb, 0xb1, 0x08, 0x25,
	0x12, 0x02, 0xd9, 0x81, 0x18, 0x62, 0x0c, 0x36, 0x36, 0xa1, 0xb0, 0x14, 0xa0, 0x94, 0xcc, 0x47,
	0x03, 0x2e, 0x78, 0x53, 0x97, 0xac, 0x41, 0x4e, 0xdf, 0x47, 0xd2, 0x4c, 0x23, 0xb3, 0x5e, 0xdc,
	0xaa, 0x6c, 0x9a, 0x9b, 0xee, 0x8e, 0x84, 0xdf, 0x61, 0x8a, 0x79, 0x36, 0xe9, 0xbe, 0x86, 0x92,
	0x0e, 0xfd, 0xe6, 0x19, 0x2e, 0x18, 0xcd, 0x68, 0xa6, 0x91, 0x5a, 0x70, 0x84, 0xc9, 0xb9, 0xab,
	0x00, 0x87, 0x38, 0x53, 0xa0, 0x02, 0x69, 0x3e, 0x8c, 0xd9, 0xd3, 0x7c, 0xe8, 0xd6, 0xa1, 0xdc,
	0xc1, 0x11, 0x2a, 0x9c, 0x2f, 0x48, 0xcf, 0x0a, 0x5e, 0xc1, 0xd2, 0x9e, 0x08, 0x02, 0x0c, 0x8d,
	0x4e, 0x6c, 0xa2, 0x2e, 0x44, 0x64, 0xf0, 0x05, 0x2f, 0xf6, 0xc8, 0x3f, 0x00, 0x83, 0x08, 0x99,
	0xc2, 0x1e, 0x0f, 0x30, 0x86, 0x26, 0x22, 0xba, 0xff, 0x81, 0x08, 0x15, 0x86, 0xca, 0x34, 0x5a,
	0xf0, 0xa6, 0xae, 0xfb, 0x39, 0x0b, 0xf9, 0x69, 0xbb, 0xe4, 0xe1, 0x5d, 0x6b, 0xbb, 0xff, 0xdd,
	0xde, 0xd4, 0xff, 0xf5, 0x45, 0x14, 0x6c, 0xbb, 0xe3, 0x88, 0x07, 0x2c, 0xba, 0x3e, 0xbb, 0xc4,
	0xeb, 0x9d, 0xf6, 0x69, 0xef, 0xc5, 0xd9, 0xd1, 0xc9, 0x9e, 0xb7, 0xff, 0x7c, 0xff, 0xa4, 0xe7,
	0xea, 0x06, 0xf5, 0x9b, 0x2a, 0xae, 0x46, 0x53, 0x6d, 0xac, 0x43, 0xaa, 0x90, 0x19, 0xa2, 0x8c,
	0xcf, 0xd3, 0x66, 0xb2, 0x8b, 0xec, 0x5c, 0x17, 0xf7, 0xfa, 0xcf, 0xfd, 0xd0, 0xff, 0x1a, 0x38,
	0x52, 0x31, 0x35, 0x91, 0xd4, 0x69, 0xa4, 0xd6, 0x2b, 0x5b, 0x25, 0xab, 0x73, 0xd7, 0xc4, 0xbc,
	0x38, 0xa7, 0x5f, 0x4e, 0x5d, 0x8f, 0x91, 0x2e, 0x19, 0x72, 0x63, 0xdb, 0x79, 0xbb, 0x44, 0x49,
	0xf3, 0xd3, 0x79, 0xbb, 0x44, 0xa9, 0xa3, 0x57, 0x1c, 0xdf, 0x49, 0x5a, 0xb0, 0x51, 0xe3, 0x90,
	0x47, 0x90, 0x1f, 0x58, 0xa1, 0x25, 0x05, 0x33, 0x32, 0x65, 0x7b, 0x4e, 0x2c, 0xff, 0x6e, 0xe9,
	0xf6, 0xa6, 0x9e, 0xb7, 0x9a, 0x6c, 0xb8, 0xde, 0xac, 0x98, 0xfc, 0x0f, 0x10, 0xdb, 0x5d, 0x15,
	0xd1, 0xa2, 0x3e, 0xde, 0xd6, 0xbe, 0x91, 0x22, 0x34, 0xb5, 0x89, 0x3c, 0x69, 0x40, 0x56, 0x31,
	0x5f, 0xd2, 0x52, 0x23, 0x33, 0xad, 0x9b, 0x71, 0x9a, 0x8c, 0xbe, 0xae, 0x62, 0xbe, 0xe6, 0x2a,
	0x2f, 0xe0, 0x8a, 0x73, 0xba, 0x8a, 0x07, 0xcc, 0x47, 0x49, 0x2b, 0x0b, 0x98, 0xe2, 0x1c, 0x69,
	0x42, 0xc1, 0x5a, 0x9a, 0xee, 0xcf, 0x05, 0x74, 0x77, 0x69, 0x3d, 0x5e, 0x13, 0x89, 0xd1, 0x51,
	0x87, 0x56, 0xed, 0x1a, 0x5a, 0x4f, 0x3f, 0x8f, 0xb6, 0xda, 0x57, 0x4c, 0xb1, 0x88, 0x2e, 0x1b,
	0x79, 0x13, 0x91, 0x66, 0x1d, 0x1c, 0xfb, 0x14, 0xa4, 0x00, 0xb9, 0x8e, 0xd7, 0x3e, 0xe8, 0x55,
	0xff, 0x20, 0x00, 0xce, 0xcb, 0xd3, 0xe3, 0xa3, 0xee, 0xb3, 0x6a, 0x6a, 0xeb, 0x6b, 0x1a, 0x8a,
	0x7a, 0xca, 0xba, 0x18, 0x5d, 0xf1, 0x01, 0x92, 0xc7, 0x90, 0xd5, 0x7b, 0x4d, 0x96, 0xad, 0xbe,
	0x89, 0x0f, 0xa2, 0x46, 0x92, 0x21, 0xbb, 0x92, 0x6e, 0xe5, 0xe3, 0x97, 0x6f, 0x9f, 0xd2, 0x79,
	0xe2, 0xb4, 0xcc, 0xca, 0x92, 0x27, 0xe0, 0xec, 0x99, 0xe1, 0x20, 0xf7, 0x16, 0x6e, 0x8a, 0x4e,
	0x2e, 0xb4, 0xbb, 0x6c, 0xd0, 0x45, 0x37, 0x46, 0x6f, 0xa7, 0x9a, 0xe4, 0x29, 0x64, 0x0e, 0x51,
	0x91, 0xaa, 0xad, 0xbe, 0x5b, 0xce, 0x85, 0xf8, 0x15, 0x83, 0x2f, 0x93, 0xa2, 0xc5, 0xb7, 0xde,
	0xf3, 0xe1, 0x07, 0xd2, 0x06, 0xe7, 0x74, 0x3c, 0xfc, 0xd5, 0x16, 0x62, 0x8a, 0xda, 0x1c, 0xc5,
	0x01, 0x38, 0x76, 0xf1, 0xc9, 0x8a, 0x85, 0xcc, 0x7d, 0x03, 0x3f, 0xe3, 0x69, 0x26, 0x79, 0xfa,
	0x8e, 0xf9, 0x68, 0x1f, 0x7c, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x80, 0x4f, 0x42, 0x1b, 0xc9, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	// List Blog
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Create Blog
	Create(ctx context.Context, in *BlogData, opts ...grpc.CallOption) (*BlogResponse, error)
	// Get Blog
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BlogResponse, error)
	// Update Blog
	Update(ctx context.Context, in *BlogData, opts ...grpc.CallOption) (*BlogResponse, error)
	// Delete Blog
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*BlogResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Create(ctx context.Context, in *BlogData, opts ...grpc.CallOption) (*BlogResponse, error) {
	out := new(BlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BlogResponse, error) {
	out := new(BlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Update(ctx context.Context, in *BlogData, opts ...grpc.CallOption) (*BlogResponse, error) {
	out := new(BlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*BlogResponse, error) {
	out := new(BlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	// List Blog
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Create Blog
	Create(context.Context, *BlogData) (*BlogResponse, error)
	// Get Blog
	Get(context.Context, *GetRequest) (*BlogResponse, error)
	// Update Blog
	Update(context.Context, *BlogData) (*BlogResponse, error)
	// Delete Blog
	Delete(context.Context, *DeleteRequest) (*BlogResponse, error)
}

// UnimplementedBlogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func (*UnimplementedBlogServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBlogServiceServer) Create(ctx context.Context, req *BlogData) (*BlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBlogServiceServer) Get(ctx context.Context, req *GetRequest) (*BlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBlogServiceServer) Update(ctx context.Context, req *BlogData) (*BlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBlogServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*BlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Create(ctx, req.(*BlogData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Update(ctx, req.(*BlogData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BlogService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BlogService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BlogService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BlogService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BlogService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}
