// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blog.proto

package blog

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_INVALID   Status = 0
	Status_DRAFT     Status = 1
	Status_PENDING   Status = 2
	Status_PUBLISHED Status = 3
	Status_REMOVE    Status = 4
)

var Status_name = map[int32]string{
	0: "INVALID",
	1: "DRAFT",
	2: "PENDING",
	3: "PUBLISHED",
	4: "REMOVE",
}

var Status_value = map[string]int32{
	"INVALID":   0,
	"DRAFT":     1,
	"PENDING":   2,
	"PUBLISHED": 3,
	"REMOVE":    4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

type Type int32

const (
	Type_PUBLIC  Type = 0
	Type_PRIVATE Type = 1
)

var Type_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
}

var Type_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

type ListRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListResponse struct {
	Data                 *ListResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetData() *ListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListResponse_Data struct {
	Blogs                []*BlogData `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	TotalBlogs           int32       `protobuf:"varint,2,opt,name=totalBlogs,proto3" json:"totalBlogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse_Data) Reset()         { *m = ListResponse_Data{} }
func (m *ListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ListResponse_Data) ProtoMessage()    {}
func (*ListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1, 0}
}
func (m *ListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse_Data.Unmarshal(m, b)
}
func (m *ListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse_Data.Marshal(b, m, deterministic)
}
func (m *ListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse_Data.Merge(m, src)
}
func (m *ListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ListResponse_Data.Size(m)
}
func (m *ListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse_Data proto.InternalMessageInfo

func (m *ListResponse_Data) GetBlogs() []*BlogData {
	if m != nil {
		return m.Blogs
	}
	return nil
}

func (m *ListResponse_Data) GetTotalBlogs() int32 {
	if m != nil {
		return m.TotalBlogs
	}
	return 0
}

type CreateRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Header               string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Background           string   `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ReadTime             int32    `protobuf:"varint,6,opt,name=readTime,proto3" json:"readTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateRequest) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *CreateRequest) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *CreateRequest) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *CreateRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateRequest) GetReadTime() int32 {
	if m != nil {
		return m.ReadTime
	}
	return 0
}

type CreateResponse struct {
	Data                 *CreateResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetData() *CreateResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateResponse_Data struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse_Data) Reset()         { *m = CreateResponse_Data{} }
func (m *CreateResponse_Data) String() string { return proto.CompactTextString(m) }
func (*CreateResponse_Data) ProtoMessage()    {}
func (*CreateResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3, 0}
}
func (m *CreateResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse_Data.Unmarshal(m, b)
}
func (m *CreateResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse_Data.Marshal(b, m, deterministic)
}
func (m *CreateResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse_Data.Merge(m, src)
}
func (m *CreateResponse_Data) XXX_Size() int {
	return xxx_messageInfo_CreateResponse_Data.Size(m)
}
func (m *CreateResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse_Data proto.InternalMessageInfo

func (m *CreateResponse_Data) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

type ViewRequest struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewRequest) Reset()         { *m = ViewRequest{} }
func (m *ViewRequest) String() string { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()    {}
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{4}
}
func (m *ViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewRequest.Unmarshal(m, b)
}
func (m *ViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewRequest.Marshal(b, m, deterministic)
}
func (m *ViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewRequest.Merge(m, src)
}
func (m *ViewRequest) XXX_Size() int {
	return xxx_messageInfo_ViewRequest.Size(m)
}
func (m *ViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewRequest proto.InternalMessageInfo

func (m *ViewRequest) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

type ViewResponse struct {
	Data                 *ViewResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{5}
}
func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (m *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(m, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetData() *ViewResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ViewResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ViewResponse_Data struct {
	Blog                 *BlogData `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ViewResponse_Data) Reset()         { *m = ViewResponse_Data{} }
func (m *ViewResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ViewResponse_Data) ProtoMessage()    {}
func (*ViewResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{5, 0}
}
func (m *ViewResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse_Data.Unmarshal(m, b)
}
func (m *ViewResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse_Data.Marshal(b, m, deterministic)
}
func (m *ViewResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse_Data.Merge(m, src)
}
func (m *ViewResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ViewResponse_Data.Size(m)
}
func (m *ViewResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse_Data proto.InternalMessageInfo

func (m *ViewResponse_Data) GetBlog() *BlogData {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateRequest struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty"`
	Header               string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Background           string   `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{6}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

func (m *UpdateRequest) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *UpdateRequest) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *UpdateRequest) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *UpdateRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateResponse struct {
	Data                 *UpdateResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{7}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetData() *UpdateResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateResponse_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse_Data) Reset()         { *m = UpdateResponse_Data{} }
func (m *UpdateResponse_Data) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse_Data) ProtoMessage()    {}
func (*UpdateResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{7, 0}
}
func (m *UpdateResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse_Data.Unmarshal(m, b)
}
func (m *UpdateResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse_Data.Marshal(b, m, deterministic)
}
func (m *UpdateResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse_Data.Merge(m, src)
}
func (m *UpdateResponse_Data) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse_Data.Size(m)
}
func (m *UpdateResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse_Data proto.InternalMessageInfo

type RemoveRequest struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{8}
}
func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

type RemoveResponse struct {
	Data                 *RemoveResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{9}
}
func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func (m *RemoveResponse) GetData() *RemoveResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoveResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RemoveResponse_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse_Data) Reset()         { *m = RemoveResponse_Data{} }
func (m *RemoveResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse_Data) ProtoMessage()    {}
func (*RemoveResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{9, 0}
}
func (m *RemoveResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse_Data.Unmarshal(m, b)
}
func (m *RemoveResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse_Data.Marshal(b, m, deterministic)
}
func (m *RemoveResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse_Data.Merge(m, src)
}
func (m *RemoveResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse_Data.Size(m)
}
func (m *RemoveResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse_Data proto.InternalMessageInfo

type PublishRequest struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{10}
}
func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

type PublishResponse struct {
	Data                 *PublishResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{11}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetData() *PublishResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PublishResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PublishResponse_Data struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse_Data) Reset()         { *m = PublishResponse_Data{} }
func (m *PublishResponse_Data) String() string { return proto.CompactTextString(m) }
func (*PublishResponse_Data) ProtoMessage()    {}
func (*PublishResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{11, 0}
}
func (m *PublishResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse_Data.Unmarshal(m, b)
}
func (m *PublishResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse_Data.Marshal(b, m, deterministic)
}
func (m *PublishResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse_Data.Merge(m, src)
}
func (m *PublishResponse_Data) XXX_Size() int {
	return xxx_messageInfo_PublishResponse_Data.Size(m)
}
func (m *PublishResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse_Data proto.InternalMessageInfo

func (m *PublishResponse_Data) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Comment struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	CreateTime           int64    `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{12}
}
func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Comment) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type BlogData struct {
	BlogID               string   `protobuf:"bytes,1,opt,name=blogID,proto3" json:"blogID,omitempty" gorm:"primary_key"`
	Header               string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Background           string   `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Status               Status   `protobuf:"varint,7,opt,name=status,proto3,enum=blog.Status" json:"status,omitempty"`
	Type                 Type     `protobuf:"varint,8,opt,name=type,proto3,enum=blog.Type" json:"type,omitempty"`
	UserID               string   `protobuf:"bytes,9,opt,name=userID,proto3" json:"userID,omitempty"`
	UserDName            string   `protobuf:"bytes,10,opt,name=userDName,proto3" json:"userDName,omitempty" gorm:"-"`
	UserAvatar           string   `protobuf:"bytes,11,opt,name=userAvatar,proto3" json:"userAvatar,omitempty" gorm:"-"`
	ReadTime             int32    `protobuf:"varint,12,opt,name=readTime,proto3" json:"readTime,omitempty"`
	Likes                int64    `protobuf:"varint,13,opt,name=likes,proto3" json:"likes,omitempty"`
	Views                int64    `protobuf:"varint,14,opt,name=views,proto3" json:"views,omitempty"`
	Tags                 []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty" gorm:"-"`
	TagStr               string   `protobuf:"bytes,16,opt,name=tagStr,proto3" json:"tagStr,omitempty" json:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogData) Reset()         { *m = BlogData{} }
func (m *BlogData) String() string { return proto.CompactTextString(m) }
func (*BlogData) ProtoMessage()    {}
func (*BlogData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{13}
}
func (m *BlogData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogData.Unmarshal(m, b)
}
func (m *BlogData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogData.Marshal(b, m, deterministic)
}
func (m *BlogData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogData.Merge(m, src)
}
func (m *BlogData) XXX_Size() int {
	return xxx_messageInfo_BlogData.Size(m)
}
func (m *BlogData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogData.DiscardUnknown(m)
}

var xxx_messageInfo_BlogData proto.InternalMessageInfo

func (m *BlogData) GetBlogID() string {
	if m != nil {
		return m.BlogID
	}
	return ""
}

func (m *BlogData) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *BlogData) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func (m *BlogData) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *BlogData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlogData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BlogData) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_INVALID
}

func (m *BlogData) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_PUBLIC
}

func (m *BlogData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *BlogData) GetUserDName() string {
	if m != nil {
		return m.UserDName
	}
	return ""
}

func (m *BlogData) GetUserAvatar() string {
	if m != nil {
		return m.UserAvatar
	}
	return ""
}

func (m *BlogData) GetReadTime() int32 {
	if m != nil {
		return m.ReadTime
	}
	return 0
}

func (m *BlogData) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *BlogData) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *BlogData) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BlogData) GetTagStr() string {
	if m != nil {
		return m.TagStr
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{14}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterEnum("blog.Status", Status_name, Status_value)
	proto.RegisterEnum("blog.Type", Type_name, Type_value)
	proto.RegisterType((*ListRequest)(nil), "blog.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "blog.ListResponse")
	proto.RegisterType((*ListResponse_Data)(nil), "blog.ListResponse.Data")
	proto.RegisterType((*CreateRequest)(nil), "blog.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "blog.CreateResponse")
	proto.RegisterType((*CreateResponse_Data)(nil), "blog.CreateResponse.Data")
	proto.RegisterType((*ViewRequest)(nil), "blog.ViewRequest")
	proto.RegisterType((*ViewResponse)(nil), "blog.ViewResponse")
	proto.RegisterType((*ViewResponse_Data)(nil), "blog.ViewResponse.Data")
	proto.RegisterType((*UpdateRequest)(nil), "blog.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "blog.UpdateResponse")
	proto.RegisterType((*UpdateResponse_Data)(nil), "blog.UpdateResponse.Data")
	proto.RegisterType((*RemoveRequest)(nil), "blog.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "blog.RemoveResponse")
	proto.RegisterType((*RemoveResponse_Data)(nil), "blog.RemoveResponse.Data")
	proto.RegisterType((*PublishRequest)(nil), "blog.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "blog.PublishResponse")
	proto.RegisterType((*PublishResponse_Data)(nil), "blog.PublishResponse.Data")
	proto.RegisterType((*Comment)(nil), "blog.Comment")
	proto.RegisterType((*BlogData)(nil), "blog.BlogData")
	proto.RegisterType((*Error)(nil), "blog.Error")
}

func init() { proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1) }

var fileDescriptor_6745b25902462fb1 = []byte{
	// 1243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x41, 0x73, 0xdb, 0xc4,
	0x17, 0xaf, 0x6c, 0xc7, 0x89, 0x9f, 0x63, 0xc7, 0xff, 0x6d, 0x9a, 0xbf, 0x6a, 0x98, 0x54, 0x15,
	0x65, 0xc8, 0x98, 0xda, 0x6a, 0x4d, 0x4f, 0xed, 0x05, 0xa7, 0x0e, 0x34, 0x33, 0x69, 0xda, 0x51,
	0xd2, 0xcc, 0x00, 0x07, 0x66, 0x2d, 0x6f, 0x65, 0x35, 0x92, 0x57, 0xec, 0xae, 0x12, 0x02, 0xc3,
	0xa5, 0xc3, 0x05, 0x4e, 0x0c, 0x0c, 0x17, 0xf8, 0x0a, 0x5c, 0xf8, 0x0e, 0x1c, 0xb8, 0x73, 0xef,
	0x89, 0x4f, 0xd0, 0x33, 0x07, 0x66, 0x77, 0x25, 0x47, 0x4a, 0x3c, 0x2d, 0xed, 0x01, 0x4e, 0xf6,
	0x7b, 0xef, 0xb7, 0x3f, 0xfd, 0xf6, 0xed, 0xdb, 0xf7, 0x16, 0x60, 0x14, 0x52, 0xbf, 0x17, 0x33,
	0x2a, 0x28, 0xaa, 0xc8, 0xff, 0xed, 0x37, 0x7d, 0x4a, 0xfd, 0x90, 0x38, 0x38, 0x0e, 0x1c, 0x3c,
	0x9d, 0x52, 0x81, 0x45, 0x40, 0xa7, 0x5c, 0x63, 0xda, 0xd7, 0xd5, 0x8f, 0xd7, 0xf5, 0xc9, 0xb4,
	0xcb, 0x8f, 0xb1, 0xef, 0x13, 0xe6, 0xd0, 0x58, 0x21, 0xe6, 0xa0, 0xbb, 0x7e, 0x20, 0x26, 0xc9,
	0xa8, 0xe7, 0xd1, 0xc8, 0xf1, 0xa9, 0x4f, 0x1d, 0xe5, 0x1e, 0x25, 0x8f, 0x95, 0xa5, 0x0c, 0xf5,
	0x4f, 0xc3, 0xed, 0x3b, 0x50, 0xdf, 0x09, 0xb8, 0x70, 0xc9, 0x67, 0x09, 0xe1, 0x02, 0xad, 0xc2,
	0x42, 0x18, 0x44, 0x81, 0x30, 0x0d, 0xcb, 0xd8, 0x58, 0x70, 0xb5, 0x81, 0xd6, 0xa0, 0x4a, 0x1f,
	0x3f, 0xe6, 0x44, 0x98, 0x25, 0xe5, 0x4e, 0x2d, 0xfb, 0x17, 0x03, 0x96, 0xf5, 0x6a, 0x1e, 0xd3,
	0x29, 0x27, 0xe8, 0x5d, 0xa8, 0x8c, 0xb1, 0xc0, 0x6a, 0x75, 0xbd, 0xff, 0xff, 0x9e, 0xda, 0x69,
	0x1e, 0xd1, 0x1b, 0x62, 0x81, 0x5d, 0x05, 0x42, 0x57, 0x61, 0x81, 0x30, 0x46, 0x99, 0x22, 0xad,
	0xf7, 0xeb, 0x1a, 0xbd, 0x25, 0x5d, 0xae, 0x8e, 0xb4, 0x77, 0xa0, 0x22, 0x17, 0xa0, 0x6b, 0xb0,
	0x20, 0x83, 0xdc, 0x34, 0xac, 0xf2, 0x46, 0xbd, 0xdf, 0xd4, 0xd0, 0xcd, 0x90, 0xfa, 0x8a, 0x4f,
	0x07, 0xd1, 0x3a, 0x80, 0xa0, 0x02, 0x87, 0x9b, 0x0a, 0xaa, 0xa5, 0xe6, 0x3c, 0xf6, 0xaf, 0x06,
	0x34, 0xee, 0x32, 0x82, 0x05, 0xc9, 0xb6, 0xbb, 0x06, 0xd5, 0x84, 0x13, 0xb6, 0x3d, 0x54, 0x8a,
	0x6b, 0x6e, 0x6a, 0x49, 0xff, 0x84, 0xe0, 0x31, 0xd1, 0xda, 0x6a, 0x6e, 0x6a, 0xa1, 0x36, 0x2c,
	0xf1, 0x64, 0x24, 0x02, 0x11, 0x12, 0xb3, 0xac, 0x22, 0x33, 0x5b, 0x7e, 0x7d, 0x84, 0xbd, 0x43,
	0x9f, 0xd1, 0x64, 0x3a, 0x36, 0x2b, 0x2a, 0x9a, 0xf3, 0x20, 0x13, 0x16, 0x3d, 0x3a, 0x15, 0x64,
	0x2a, 0xcc, 0x05, 0x15, 0xcc, 0x4c, 0xc9, 0xca, 0x08, 0x1e, 0xef, 0x07, 0x11, 0x31, 0xab, 0x4a,
	0xf5, 0xcc, 0xb6, 0x9f, 0x1a, 0xd0, 0xcc, 0x34, 0xa7, 0x49, 0xee, 0x16, 0x92, 0x7c, 0x59, 0xe7,
	0xa2, 0x88, 0x79, 0xc5, 0x34, 0xaf, 0xa7, 0x69, 0x5e, 0x83, 0xaa, 0x0c, 0x9e, 0xa6, 0x43, 0x5b,
	0xf6, 0xdb, 0x50, 0x3f, 0x08, 0xc8, 0x71, 0x2e, 0x6b, 0x73, 0x61, 0xdf, 0x1a, 0xb0, 0xac, 0x71,
	0x2f, 0x2a, 0x87, 0x3c, 0xe2, 0x15, 0x75, 0x76, 0x52, 0x9d, 0x36, 0xa8, 0x7b, 0x93, 0xf2, 0x9e,
	0xad, 0x06, 0x15, 0xb3, 0x7f, 0x34, 0xa0, 0xf1, 0x28, 0x1e, 0x17, 0x0f, 0x7b, 0x9e, 0xec, 0x7f,
	0xf7, 0xb0, 0xed, 0x27, 0xd0, 0xcc, 0x64, 0xbd, 0xe8, 0x3c, 0x8b, 0x98, 0x57, 0xcc, 0x53, 0x55,
	0xe7, 0xc9, 0x7e, 0x07, 0x1a, 0x2e, 0x89, 0xe8, 0xd1, 0xcb, 0x52, 0x20, 0x45, 0x65, 0xc0, 0x17,
	0x89, 0x2a, 0x62, 0x5e, 0x53, 0xd4, 0x06, 0x34, 0x1f, 0x26, 0xa3, 0x30, 0xe0, 0x93, 0x97, 0xa9,
	0xfa, 0xda, 0x80, 0x95, 0x19, 0x34, 0xd5, 0xd5, 0x2b, 0xe8, 0x6a, 0xeb, 0xef, 0x9c, 0x01, 0xbd,
	0x7e, 0xf5, 0x73, 0x81, 0x45, 0xc2, 0x15, 0xf9, 0x92, 0x9b, 0x5a, 0xf6, 0x27, 0xb0, 0x78, 0x97,
	0x46, 0x91, 0xbc, 0xa9, 0x6b, 0x50, 0xc5, 0x89, 0x98, 0x50, 0x96, 0x29, 0xd5, 0x96, 0x2c, 0x07,
	0x4f, 0x5d, 0x40, 0x75, 0x87, 0xe5, 0xa7, 0xca, 0x6e, 0xce, 0x93, 0x2f, 0x87, 0x72, 0xb1, 0x1c,
	0xbe, 0xab, 0xc0, 0x52, 0x56, 0xb9, 0xa8, 0x57, 0x4c, 0xc4, 0xe6, 0xda, 0xf3, 0x67, 0x57, 0x90,
	0x4f, 0x59, 0x74, 0xdb, 0x8e, 0x59, 0x10, 0x61, 0x76, 0xf2, 0xe9, 0x21, 0x39, 0xb1, 0xff, 0x9b,
	0xca, 0x3d, 0xb3, 0xc9, 0xea, 0xb9, 0x4d, 0x5e, 0x9b, 0xe5, 0x6f, 0xd1, 0x32, 0x36, 0x9a, 0xfd,
	0x65, 0x9d, 0xeb, 0x3d, 0xe5, 0xcb, 0xb2, 0x89, 0xd6, 0xa1, 0x22, 0x4e, 0x62, 0x62, 0x2e, 0x29,
	0x0c, 0x68, 0xcc, 0xfe, 0x49, 0x4c, 0x5c, 0xe5, 0xcf, 0xb5, 0xe4, 0x5a, 0xa1, 0x25, 0x77, 0xa0,
	0x26, 0xff, 0x0d, 0x77, 0x71, 0x44, 0x4c, 0x50, 0xe9, 0x59, 0x7e, 0xfe, 0xec, 0xca, 0x92, 0x4e,
	0x4f, 0xd7, 0x76, 0x4f, 0xc3, 0xe8, 0x3a, 0x80, 0x34, 0x06, 0x47, 0x58, 0x60, 0x66, 0xd6, 0xe7,
	0x80, 0x73, 0xf1, 0x42, 0xfb, 0x5d, 0x2e, 0xb6, 0x5f, 0x3d, 0x0f, 0x0f, 0x09, 0x37, 0x1b, 0x6a,
	0xbb, 0xda, 0x90, 0xde, 0xa3, 0x80, 0x1c, 0x73, 0xb3, 0xa9, 0xbd, 0xca, 0x40, 0x16, 0x54, 0x04,
	0xf6, 0xb9, 0xb9, 0x62, 0x95, 0xcf, 0x7d, 0x4f, 0x45, 0x64, 0x86, 0x04, 0xf6, 0xf7, 0x04, 0x33,
	0x5b, 0xa7, 0x9a, 0x9e, 0x70, 0x3a, 0x55, 0x98, 0x34, 0x66, 0xdf, 0x87, 0x05, 0x55, 0x9f, 0x08,
	0x41, 0xc5, 0xa3, 0x63, 0x92, 0xce, 0x62, 0xf5, 0x5f, 0x1e, 0x4f, 0x44, 0x38, 0xc7, 0x3e, 0x49,
	0xcf, 0x3c, 0x33, 0x65, 0xe2, 0xc6, 0x44, 0xe0, 0x20, 0x4c, 0x8f, 0x3c, 0xb5, 0x3a, 0xf7, 0xa0,
	0xaa, 0x8f, 0x00, 0xd5, 0x61, 0x71, 0x7b, 0xf7, 0x60, 0xb0, 0xb3, 0x3d, 0x6c, 0x5d, 0x40, 0x35,
	0x58, 0x18, 0xba, 0x83, 0x0f, 0xf6, 0x5b, 0x86, 0xf4, 0x3f, 0xdc, 0xda, 0x1d, 0x6e, 0xef, 0x7e,
	0xd8, 0x2a, 0xa1, 0x06, 0xd4, 0x1e, 0x3e, 0xda, 0xdc, 0xd9, 0xde, 0xbb, 0xb7, 0x35, 0x6c, 0x95,
	0x11, 0x40, 0xd5, 0xdd, 0xba, 0xff, 0xe0, 0x60, 0xab, 0x55, 0xe9, 0x5c, 0x81, 0x8a, 0x3c, 0x28,
	0xe9, 0x53, 0x90, 0xbb, 0xad, 0x0b, 0x6a, 0xad, 0xbb, 0x7d, 0x30, 0xd8, 0xdf, 0x6a, 0x19, 0xfd,
	0xbf, 0xca, 0x50, 0x97, 0xc5, 0xbc, 0x47, 0xd8, 0x51, 0xe0, 0x11, 0x34, 0x84, 0x8a, 0x1c, 0xfe,
	0xe8, 0x7f, 0xf9, 0x87, 0x80, 0xba, 0xf3, 0x6d, 0x74, 0xfe, 0x6d, 0x60, 0x5f, 0x7a, 0xfa, 0xc7,
	0x9f, 0x3f, 0x94, 0x56, 0x50, 0xc3, 0x39, 0xba, 0xe9, 0xc8, 0xb0, 0x13, 0xca, 0xd5, 0x0f, 0xa0,
	0xaa, 0xa7, 0x1b, 0xba, 0x58, 0x9c, 0x75, 0x9a, 0x69, 0x75, 0xde, 0x00, 0xb4, 0xdb, 0x8a, 0x6b,
	0xd5, 0x5e, 0x99, 0x71, 0xe9, 0x4a, 0xbd, 0x6d, 0x74, 0xd0, 0x7d, 0xa8, 0xc8, 0x21, 0x94, 0xc9,
	0xca, 0x8d, 0xb6, 0x4c, 0x56, 0x7e, 0x46, 0xd9, 0xeb, 0x8a, 0xca, 0x44, 0x6b, 0x33, 0x2a, 0x79,
	0xde, 0xce, 0x97, 0xfa, 0x12, 0x7e, 0x85, 0x1e, 0x41, 0x55, 0x77, 0xeb, 0x4c, 0x5f, 0x61, 0xec,
	0x64, 0xfa, 0x8a, 0x0d, 0xdd, 0xb6, 0x14, 0x69, 0xbb, 0x6d, 0xce, 0x48, 0x13, 0x05, 0x28, 0xd0,
	0xea, 0x7e, 0x9b, 0xd1, 0x16, 0x5a, 0x79, 0x46, 0x5b, 0x6c, 0xc9, 0x73, 0x68, 0x99, 0x02, 0x9c,
	0xd2, 0x7e, 0x04, 0x8b, 0x69, 0xbb, 0x44, 0xab, 0x67, 0xba, 0xa7, 0x26, 0xbe, 0x34, 0xb7, 0xa7,
	0xda, 0x57, 0x15, 0xf3, 0x1b, 0xed, 0xcb, 0x33, 0xe6, 0x58, 0x23, 0x66, 0xd4, 0x9b, 0xbf, 0x97,
	0xbe, 0x1f, 0xfc, 0x56, 0x42, 0x3f, 0x1b, 0xba, 0xa5, 0x59, 0x83, 0x38, 0xb0, 0xbf, 0x31, 0xc0,
	0xf1, 0x69, 0xd7, 0x67, 0xb1, 0xd7, 0x9d, 0x08, 0x11, 0x77, 0x19, 0xe1, 0xa2, 0x1b, 0x05, 0x1e,
	0xa3, 0x5c, 0x57, 0x49, 0x57, 0x24, 0x82, 0xb2, 0x00, 0x87, 0x56, 0xcc, 0xe8, 0x13, 0xe2, 0x09,
	0xb4, 0x29, 0x81, 0xfc, 0xb6, 0xe3, 0xe4, 0x9e, 0xb2, 0x38, 0xe2, 0xf4, 0x90, 0x86, 0xff, 0x94,
	0xab, 0x8d, 0x22, 0x32, 0x0e, 0x92, 0xe8, 0xfd, 0x74, 0x9d, 0xe4, 0xe8, 0x97, 0x6f, 0xf6, 0x6e,
	0xb4, 0x6b, 0x21, 0xf5, 0x70, 0x38, 0xa1, 0x5c, 0x74, 0x0c, 0xa3, 0xdf, 0xc2, 0x71, 0x1c, 0x06,
	0x9e, 0x7a, 0x41, 0x3b, 0xea, 0x26, 0x9e, 0xf3, 0xb8, 0x77, 0xa0, 0x7c, 0xeb, 0xc6, 0x2d, 0x74,
	0x0b, 0x3a, 0x2e, 0x11, 0x09, 0x9b, 0x92, 0xb1, 0x75, 0x3c, 0x21, 0x53, 0x4b, 0x4c, 0x88, 0xc5,
	0x08, 0xa7, 0x09, 0xf3, 0x88, 0x35, 0xa6, 0x84, 0x5b, 0x53, 0x2a, 0x2c, 0xf2, 0x79, 0xc0, 0x45,
	0x0f, 0x55, 0xa1, 0xf2, 0x53, 0xc9, 0x58, 0xfc, 0xf8, 0x2d, 0xb8, 0x0a, 0x30, 0x22, 0x98, 0x11,
	0x36, 0x48, 0xc4, 0x04, 0x5d, 0x5c, 0x2a, 0xb5, 0x1b, 0x03, 0x35, 0x35, 0x82, 0x2f, 0xd4, 0x47,
	0xac, 0xd2, 0xa8, 0x05, 0xcd, 0x02, 0xe8, 0xc2, 0xa8, 0xaa, 0x5e, 0xe7, 0xef, 0xfd, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x49, 0x02, 0x64, 0x81, 0x2c, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	View(context.Context, *ViewRequest) (*ViewResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

// UnimplementedBlogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func (*UnimplementedBlogServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBlogServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBlogServiceServer) View(ctx context.Context, req *ViewRequest) (*ViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (*UnimplementedBlogServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBlogServiceServer) Remove(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedBlogServiceServer) Publish(ctx context.Context, req *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).View(ctx, req.(*ViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BlogService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BlogService_Create_Handler,
		},
		{
			MethodName: "View",
			Handler:    _BlogService_View_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BlogService_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _BlogService_Remove_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _BlogService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}
