// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_INVALID UserStatus = 0
	UserStatus_ACTIVE  UserStatus = 1
	UserStatus_BLOCKED UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "INVALID",
	1: "ACTIVE",
	2: "BLOCKED",
}

var UserStatus_value = map[string]int32{
	"INVALID": 0,
	"ACTIVE":  1,
	"BLOCKED": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Data                 *LoginResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetData() *LoginResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LoginResponse_Data struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse_Data) Reset()         { *m = LoginResponse_Data{} }
func (m *LoginResponse_Data) String() string { return proto.CompactTextString(m) }
func (*LoginResponse_Data) ProtoMessage()    {}
func (*LoginResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}
func (m *LoginResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse_Data.Unmarshal(m, b)
}
func (m *LoginResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse_Data.Marshal(b, m, deterministic)
}
func (m *LoginResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse_Data.Merge(m, src)
}
func (m *LoginResponse_Data) XXX_Size() int {
	return xxx_messageInfo_LoginResponse_Data.Size(m)
}
func (m *LoginResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse_Data proto.InternalMessageInfo

func (m *LoginResponse_Data) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Data                 *RegisterResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetData() *RegisterResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RegisterResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RegisterResponse_Data struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_Data) Reset()         { *m = RegisterResponse_Data{} }
func (m *RegisterResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Data) ProtoMessage()    {}
func (*RegisterResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 0}
}
func (m *RegisterResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Data.Unmarshal(m, b)
}
func (m *RegisterResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Data.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Data.Merge(m, src)
}
func (m *RegisterResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Data.Size(m)
}
func (m *RegisterResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Data proto.InternalMessageInfo

func (m *RegisterResponse_Data) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DName                string   `protobuf:"bytes,4,opt,name=dName,proto3" json:"dName,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	RegisterdTime        int64    `protobuf:"varint,7,opt,name=registerdTime,proto3" json:"registerdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetRegisterdTime() int64 {
	if m != nil {
		return m.RegisterdTime
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("user.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*LoginResponse_Data)(nil), "user.LoginResponse.Data")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*RegisterResponse_Data)(nil), "user.RegisterResponse.Data")
	proto.RegisterType((*UserData)(nil), "user.UserData")
	proto.RegisterType((*Error)(nil), "user.Error")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xc5, 0xe9, 0x6e, 0x92, 0xce, 0xb6, 0x10, 0x4c, 0x29, 0xab, 0xd0, 0x43, 0xb0, 0x38, 0x54,
	0x11, 0xca, 0x8a, 0x20, 0x2e, 0xbd, 0x95, 0x26, 0x95, 0x56, 0x44, 0x45, 0x32, 0xa5, 0x77, 0x93,
	0x1d, 0xad, 0x56, 0x24, 0xeb, 0x60, 0x7b, 0xc3, 0x8d, 0x03, 0x27, 0xee, 0x7c, 0x05, 0xff, 0xc1,
	0x1f, 0xf0, 0x0b, 0x7c, 0x08, 0xb2, 0xbd, 0x0b, 0xda, 0xaa, 0x42, 0x42, 0xbd, 0xf9, 0x79, 0xde,
	0x3c, 0xcf, 0x9b, 0x19, 0x03, 0x54, 0x1a, 0xd5, 0x64, 0xa3, 0xa4, 0x91, 0x34, 0xb0, 0xe7, 0xe1,
	0x51, 0x2e, 0x65, 0xbe, 0xc2, 0x44, 0x6c, 0x8a, 0x44, 0x94, 0xa5, 0x34, 0xc2, 0x14, 0xb2, 0xd4,
	0x9e, 0xc3, 0xce, 0x61, 0x6f, 0x21, 0xf3, 0xa2, 0xe4, 0xf8, 0xb1, 0x42, 0x6d, 0xe8, 0x10, 0xfa,
	0x36, 0xab, 0x14, 0x6b, 0x8c, 0xc9, 0x88, 0x1c, 0xef, 0xf2, 0x3f, 0xd8, 0xc6, 0x36, 0x42, 0xeb,
	0x4f, 0x52, 0x65, 0x71, 0xc7, 0xc7, 0x1a, 0xcc, 0x3e, 0xc3, 0x7e, 0xad, 0xa3, 0x37, 0xb2, 0xd4,
	0x48, 0x9f, 0x41, 0x90, 0x09, 0x23, 0x9c, 0x48, 0x34, 0x8d, 0x27, 0xae, 0xae, 0x16, 0x65, 0x32,
	0x13, 0x46, 0x70, 0xc7, 0xa2, 0x4f, 0x20, 0x44, 0xa5, 0xa4, 0x72, 0xba, 0xd1, 0x34, 0xf2, 0xf4,
	0xb9, 0xbd, 0xe2, 0x3e, 0x32, 0x3c, 0x82, 0xc0, 0x26, 0xd0, 0x03, 0x08, 0x8d, 0xfc, 0x80, 0x65,
	0x5d, 0x9e, 0x07, 0x2c, 0x85, 0x7b, 0x1c, 0xf3, 0x42, 0x1b, 0x54, 0xb7, 0xb5, 0xf2, 0x95, 0xc0,
	0xe0, 0xaf, 0x56, 0x6d, 0x27, 0x69, 0xd9, 0x79, 0xec, 0xeb, 0xbb, 0xce, 0xfa, 0x4f, 0x47, 0xa3,
	0xda, 0x51, 0x0c, 0x3d, 0x5d, 0x2d, 0x97, 0xa8, 0xb5, 0x93, 0xef, 0xf3, 0x06, 0xb2, 0x1f, 0x04,
	0xfa, 0xef, 0x34, 0x2a, 0x47, 0x3b, 0x84, 0xae, 0xd5, 0x48, 0x67, 0xb5, 0x9b, 0x1a, 0xb5, 0x7c,
	0x76, 0xfe, 0xe1, 0x73, 0xa7, 0xed, 0xd3, 0x36, 0x32, 0xbb, 0xb0, 0x49, 0x81, 0x6f, 0xa4, 0x03,
	0xf6, 0x15, 0xb1, 0x15, 0x46, 0xa8, 0x38, 0xf4, 0xaf, 0x78, 0x64, 0xd9, 0xb8, 0x16, 0xc5, 0x2a,
	0xee, 0x7a, 0xb6, 0x03, 0xf4, 0x29, 0xec, 0xab, 0xba, 0x09, 0xd9, 0x65, 0xb1, 0xc6, 0xb8, 0x37,
	0x22, 0xc7, 0x3b, 0xbc, 0x7d, 0xc9, 0x5e, 0x42, 0xe8, 0x8c, 0x53, 0x0a, 0xc1, 0x52, 0x66, 0x7e,
	0x1c, 0x21, 0x77, 0x67, 0xeb, 0x7e, 0x8d, 0x5a, 0x8b, 0xbc, 0xa9, 0xbe, 0x81, 0xe3, 0x29, 0x80,
	0x35, 0xff, 0xd6, 0x08, 0x53, 0x69, 0x1a, 0x41, 0x2f, 0xbd, 0xb8, 0x3a, 0x5d, 0xa4, 0xb3, 0xc1,
	0x1d, 0x0a, 0xd0, 0x3d, 0x3d, 0xbb, 0x4c, 0xaf, 0xe6, 0x03, 0x62, 0x03, 0xaf, 0x16, 0x6f, 0xce,
	0x5e, 0xcf, 0x67, 0x83, 0xce, 0xf4, 0x3b, 0x81, 0xc8, 0x25, 0xa1, 0xda, 0x16, 0x4b, 0xa4, 0xe7,
	0x10, 0xba, 0xa5, 0xa3, 0xb4, 0xb5, 0x81, 0x6e, 0x43, 0x86, 0x0f, 0x6e, 0xd8, 0x4a, 0x76, 0xf0,
	0xe5, 0xe7, 0xaf, 0x6f, 0x9d, 0xbb, 0x6c, 0x37, 0xd9, 0x3e, 0x4f, 0x56, 0x36, 0x74, 0x42, 0xc6,
	0x94, 0x43, 0xbf, 0x99, 0x36, 0x7d, 0x78, 0x7d, 0xfa, 0x5e, 0xed, 0xf0, 0xe6, 0xa5, 0x60, 0x8f,
	0x9c, 0xe0, 0x7d, 0xb6, 0x67, 0x05, 0x9b, 0xc6, 0x9c, 0x90, 0xf1, 0xfb, 0xae, 0xfb, 0x82, 0x2f,
	0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x45, 0xb3, 0xda, 0xb4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
