// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_UNKNOWN Role = 0
)

var Role_name = map[int32]string{
	0: "UNKNOWN",
}

var Role_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type Source int32

const (
	Source_ORIGIN Source = 0
)

var Source_name = map[int32]string{
	0: "ORIGIN",
}

var Source_value = map[string]int32{
	"ORIGIN": 0,
}

func (x Source) String() string {
	return proto.EnumName(Source_name, int32(x))
}

func (Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
	Gender_OTHER  Gender = 2
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}

var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Data                 *LoginResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetData() *LoginResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LoginResponse_Data struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	DName                string   `protobuf:"bytes,3,opt,name=dName,proto3" json:"dName,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role                 Role     `protobuf:"varint,5,opt,name=role,proto3,enum=user.Role" json:"role,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse_Data) Reset()         { *m = LoginResponse_Data{} }
func (m *LoginResponse_Data) String() string { return proto.CompactTextString(m) }
func (*LoginResponse_Data) ProtoMessage()    {}
func (*LoginResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}
func (m *LoginResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse_Data.Unmarshal(m, b)
}
func (m *LoginResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse_Data.Marshal(b, m, deterministic)
}
func (m *LoginResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse_Data.Merge(m, src)
}
func (m *LoginResponse_Data) XXX_Size() int {
	return xxx_messageInfo_LoginResponse_Data.Size(m)
}
func (m *LoginResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse_Data proto.InternalMessageInfo

func (m *LoginResponse_Data) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginResponse_Data) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginResponse_Data) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *LoginResponse_Data) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *LoginResponse_Data) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN
}

func (m *LoginResponse_Data) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	DName                string   `protobuf:"bytes,4,opt,name=dName,proto3" json:"dName,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *RegisterRequest) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *RegisterRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	Data                 *RegisterResponse_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetData() *RegisterResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RegisterResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type RegisterResponse_Data struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_Data) Reset()         { *m = RegisterResponse_Data{} }
func (m *RegisterResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Data) ProtoMessage()    {}
func (*RegisterResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 0}
}
func (m *RegisterResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Data.Unmarshal(m, b)
}
func (m *RegisterResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Data.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Data.Merge(m, src)
}
func (m *RegisterResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Data.Size(m)
}
func (m *RegisterResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Data proto.InternalMessageInfo

func (m *RegisterResponse_Data) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" gorm:"primary_key"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" gorm:"unique_index"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DName                string   `protobuf:"bytes,4,opt,name=dName,proto3" json:"dName,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty" gorm:"unique;not null"`
	RegisteredTime       int64    `protobuf:"varint,7,opt,name=registeredTime,proto3" json:"registeredTime,omitempty"`
	Role                 Role     `protobuf:"varint,8,opt,name=role,proto3,enum=user.Role" json:"role,omitempty"`
	RegisterSource       Source   `protobuf:"varint,9,opt,name=registerSource,proto3,enum=user.Source" json:"registerSource,omitempty"`
	Gender               Gender   `protobuf:"varint,10,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Locked               bool     `protobuf:"varint,11,opt,name=locked,proto3" json:"locked,omitempty"`
	LockTime             int64    `protobuf:"varint,12,opt,name=lockTime,proto3" json:"lockTime,omitempty"`
	LockReason           string   `protobuf:"bytes,13,opt,name=lockReason,proto3" json:"lockReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetRegisteredTime() int64 {
	if m != nil {
		return m.RegisteredTime
	}
	return 0
}

func (m *UserData) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN
}

func (m *UserData) GetRegisterSource() Source {
	if m != nil {
		return m.RegisterSource
	}
	return Source_ORIGIN
}

func (m *UserData) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

func (m *UserData) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *UserData) GetLockTime() int64 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

func (m *UserData) GetLockReason() string {
	if m != nil {
		return m.LockReason
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterEnum("user.Role", Role_name, Role_value)
	proto.RegisterEnum("user.Source", Source_name, Source_value)
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*LoginResponse_Data)(nil), "user.LoginResponse.Data")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*RegisterResponse_Data)(nil), "user.RegisterResponse.Data")
	proto.RegisterType((*UserData)(nil), "user.UserData")
	proto.RegisterType((*Error)(nil), "user.Error")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0x89, 0x1d, 0x92, 0x93, 0x00, 0xb9, 0x43, 0x6e, 0xb0, 0x72, 0xaf, 0x20, 0xb5, 0xaa,
	0x2a, 0x8d, 0xda, 0xa4, 0x0d, 0x5d, 0xd1, 0x55, 0x11, 0x81, 0xa2, 0x42, 0xa8, 0x06, 0x50, 0x97,
	0x68, 0xb0, 0x07, 0xd7, 0xc2, 0xf6, 0x84, 0xb1, 0x4d, 0xcb, 0xb2, 0x5d, 0x75, 0xdf, 0x7d, 0xf7,
	0x7d, 0x82, 0x3e, 0x48, 0xf7, 0x6c, 0xda, 0x27, 0xe0, 0x09, 0xaa, 0x99, 0xb1, 0xf3, 0x27, 0x58,
	0xa0, 0xee, 0xe6, 0x3b, 0xe7, 0xf3, 0xe7, 0x73, 0xbe, 0x33, 0x67, 0x00, 0x92, 0x88, 0xf2, 0xce,
	0x90, 0xb3, 0x98, 0x21, 0x5d, 0x9c, 0x1b, 0xff, 0xbb, 0x8c, 0xb9, 0x3e, 0xed, 0x92, 0xa1, 0xd7,
	0x25, 0x61, 0xc8, 0x62, 0x12, 0x7b, 0x2c, 0x8c, 0x14, 0xa7, 0xf1, 0xd4, 0xf5, 0xe2, 0xf7, 0xc9,
	0x69, 0xc7, 0x66, 0x41, 0xd7, 0x65, 0x2e, 0xeb, 0xca, 0xf0, 0x69, 0x72, 0x26, 0x91, 0x04, 0xf2,
	0xa4, 0xe8, 0xd6, 0x36, 0x54, 0xf6, 0x98, 0xeb, 0x85, 0x98, 0x5e, 0x24, 0x34, 0x8a, 0x51, 0x03,
	0x8a, 0xe2, 0x27, 0x21, 0x09, 0xa8, 0xa9, 0x35, 0xb5, 0x56, 0x09, 0x8f, 0xb0, 0xc8, 0x0d, 0x49,
	0x14, 0x7d, 0x60, 0xdc, 0x31, 0x73, 0x2a, 0x97, 0x61, 0xeb, 0x53, 0x0e, 0x16, 0x52, 0xa1, 0x68,
	0xc8, 0xc2, 0x88, 0xa2, 0x27, 0xa0, 0x3b, 0x24, 0x26, 0x52, 0xa5, 0xdc, 0x33, 0x3b, 0xb2, 0x8f,
	0x29, 0x4a, 0x67, 0x8b, 0xc4, 0x04, 0x4b, 0x16, 0x7a, 0x00, 0x06, 0xe5, 0x9c, 0x71, 0x29, 0x5c,
	0xee, 0x95, 0x15, 0xbd, 0x2f, 0x42, 0x58, 0x65, 0x1a, 0xdf, 0x34, 0xd0, 0xc5, 0x17, 0xa8, 0x0e,
	0x05, 0x91, 0xdd, 0xdd, 0x4a, 0x2b, 0x4c, 0x51, 0x56, 0xfb, 0x40, 0xd4, 0x9e, 0x1b, 0xd7, 0x2e,
	0x30, 0xaa, 0x81, 0xe1, 0xc8, 0x44, 0x5e, 0x26, 0x14, 0x10, 0x4a, 0xe4, 0x92, 0xc4, 0x84, 0x9b,
	0xba, 0x52, 0x52, 0x08, 0xad, 0x82, 0xce, 0x99, 0x4f, 0x4d, 0xa3, 0xa9, 0xb5, 0x16, 0x7b, 0xa0,
	0x8a, 0xc1, 0xcc, 0xa7, 0x58, 0xc6, 0x85, 0x5a, 0xcc, 0xce, 0x69, 0x68, 0x16, 0x94, 0x9a, 0x04,
	0xd6, 0x0f, 0x0d, 0x96, 0x30, 0x75, 0xbd, 0x28, 0xa6, 0xfc, 0x2f, 0xfd, 0x44, 0x2d, 0x58, 0xb2,
	0x59, 0x78, 0xe6, 0xf1, 0xe0, 0x6d, 0x46, 0x51, 0x95, 0xcf, 0x86, 0xc7, 0x9d, 0xe9, 0xb7, 0x77,
	0x66, 0x4c, 0x75, 0x56, 0x03, 0x83, 0x06, 0xc4, 0xf3, 0xb3, 0xca, 0x25, 0xb0, 0xbe, 0x68, 0x50,
	0x1d, 0x57, 0x9e, 0x0e, 0xb0, 0x3b, 0x35, 0xc0, 0xff, 0x52, 0x13, 0x66, 0x58, 0xf7, 0x9c, 0x61,
	0x33, 0x1d, 0xa1, 0x09, 0xf3, 0x51, 0x62, 0xdb, 0x34, 0x8a, 0xa4, 0x7c, 0x11, 0x67, 0xd0, 0xfa,
	0x95, 0x87, 0xe2, 0x71, 0x44, 0xb9, 0xa4, 0x75, 0xa6, 0x27, 0xbd, 0x59, 0xbf, 0xb9, 0x5e, 0x43,
	0x2e, 0xe3, 0xc1, 0x86, 0x35, 0xe4, 0x5e, 0x40, 0xf8, 0xd5, 0xc9, 0x39, 0xbd, 0xb2, 0x46, 0x37,
	0x60, 0x7d, 0xc2, 0x6d, 0xe9, 0xe8, 0xe6, 0xca, 0xcd, 0xf5, 0xda, 0xb2, 0xfa, 0x22, 0x09, 0xbd,
	0x8b, 0x84, 0x9e, 0x78, 0xa1, 0x43, 0x3f, 0x5a, 0x77, 0x8c, 0x21, 0x3f, 0x33, 0x86, 0xfb, 0x99,
	0xfb, 0x6c, 0xca, 0xdc, 0xcd, 0xc6, 0xcd, 0xf5, 0x5a, 0x7d, 0xf2, 0xdf, 0x2f, 0x43, 0x16, 0x37,
	0xc3, 0xc4, 0xf7, 0xad, 0xd4, 0x78, 0xf4, 0x08, 0x16, 0x79, 0xea, 0x28, 0x75, 0x8e, 0xbc, 0x80,
	0x9a, 0xf3, 0x4d, 0xad, 0x95, 0xc7, 0x33, 0xd1, 0xd1, 0x85, 0x2c, 0xde, 0x71, 0x21, 0x5f, 0x8c,
	0x75, 0x0e, 0x59, 0xc2, 0x6d, 0x6a, 0x96, 0x24, 0xb3, 0xa2, 0x98, 0x2a, 0x86, 0x67, 0x38, 0xe8,
	0x21, 0x14, 0x5c, 0x1a, 0x3a, 0x94, 0x9b, 0x30, 0xc9, 0xde, 0x91, 0x31, 0x9c, 0xe6, 0x44, 0xb7,
	0x3e, 0xb3, 0xcf, 0xa9, 0x63, 0x96, 0xe5, 0xa8, 0x52, 0x24, 0x7c, 0x13, 0x27, 0x59, 0x75, 0x45,
	0x56, 0x3d, 0xc2, 0x68, 0x15, 0x40, 0x9c, 0x31, 0x25, 0x11, 0x0b, 0xcd, 0x05, 0xe9, 0xd2, 0x44,
	0xc4, 0xda, 0x07, 0x43, 0xde, 0x0b, 0x84, 0x40, 0xb7, 0x99, 0xa3, 0x76, 0xc3, 0xc0, 0xf2, 0x2c,
	0x2e, 0x47, 0x40, 0xa3, 0x88, 0xb8, 0xd9, 0x1a, 0x67, 0x50, 0x94, 0xe2, 0xd0, 0x58, 0x38, 0xac,
	0x06, 0x95, 0xa2, 0xf6, 0x32, 0xe8, 0xc2, 0x0c, 0x54, 0x86, 0xf9, 0xe3, 0xc1, 0x9b, 0xc1, 0xc1,
	0xbb, 0x41, 0x75, 0xae, 0x5d, 0x83, 0x42, 0xda, 0x27, 0x40, 0xe1, 0x00, 0xef, 0xee, 0xec, 0x8a,
	0xe8, 0x63, 0x28, 0xa8, 0xfe, 0x50, 0x11, 0xf4, 0xfd, 0x57, 0x7b, 0xfd, 0xea, 0x9c, 0xc8, 0x6f,
	0xf7, 0xe5, 0x59, 0x43, 0x25, 0x30, 0x0e, 0x8e, 0x5e, 0xf7, 0x71, 0x35, 0xd7, 0xfb, 0xae, 0x41,
	0x59, 0x5c, 0xc5, 0x43, 0xca, 0x2f, 0x3d, 0x9b, 0xa2, 0x6d, 0x30, 0xe4, 0xfb, 0x85, 0xd0, 0xd4,
	0x63, 0x26, 0x17, 0xbd, 0xb1, 0x7c, 0xcb, 0x03, 0x67, 0xd5, 0x3e, 0xff, 0xfc, 0xfd, 0x35, 0xb7,
	0x68, 0x95, 0xba, 0x97, 0xcf, 0xbb, 0xbe, 0x48, 0x6d, 0x68, 0x6d, 0x84, 0xa1, 0x98, 0xad, 0x11,
	0xfa, 0x77, 0x76, 0xad, 0x94, 0x5a, 0xfd, 0xf6, 0x6d, 0xb3, 0x56, 0xa4, 0xe0, 0x3f, 0x56, 0x45,
	0x08, 0x66, 0xd3, 0xdc, 0xd0, 0xda, 0xa7, 0x05, 0xf9, 0x9c, 0xaf, 0xff, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x92, 0xf7, 0x3b, 0xb3, 0x2f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
